# Generated by Django 5.2.1 on 2025-06-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('available', models.TextField(blank=True)),
                ('acquired', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('found', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('repeatable', models.BooleanField(default=False)),
            ],
        ),
    ]
