# Generated by Django 5.2.1 on 2025-06-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout3', '0002_alter_quest_acquired_alter_quest_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobblehead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('acquired', models.BooleanField(default=False)),
            ],
        ),
    ]
