# Generated by Django 5.2.1 on 2025-06-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout3', '0005_nukacolaquantum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('acquired', models.BooleanField(default=False)),
            ],
        ),
    ]
