# Generated by Django 5.2.1 on 2025-06-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fallout3', '0008_teddybearlocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeddyBearLocation',
            new_name='TeddyBear',
        ),
    ]
