# Generated by Django 5.2.1 on 2025-06-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout3', '0009_rename_teddybearlocation_teddybear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='repeatable',
        ),
        migrations.AddField(
            model_name='quest',
            name='rewards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
