# Generated by Django 5.2.1 on 2025-06-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fallout3', '0010_remove_quest_repeatable_quest_rewards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='available',
            new_name='note',
        ),
    ]
