# Generated by Django 5.2.1 on 2025-06-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fallout3', '0013_rename_description_achievement_requirement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='unlocked',
            new_name='acquired',
        ),
    ]
